In [8]:
import pandas as pd

url = 'http://www.weather.com.cn/textFC/hb.shtml'
pd.read_html(url, header=1, index_col=[0, 1])[0]

          天气现象     风向风力  最高气温 天气现象.1   风向风力.1  最低气温 Unnamed: 8
省/直辖市 城市
北京    北京    小雨  东南风 <3级    28     多云  东北风 <3级    16         详情
      海淀    小雨  西北风 <3级    28     多云   北风 <3级    15         详情
      朝阳    小雨  东南风 <3级    27     多云  东北风 <3级    16         详情
      顺义    小雨  东南风 <3级    27     多云  东北风 <3级    15         详情
      怀柔    小雨  东南风 <3级    27     多云   北风 <3级    14         详情
      通州    小雨   东风 <3级    27     多云   东风 <3级    15         详情
      昌平    小雨  东南风 <3级    26     多云  西北风 <3级    15         详情
      延庆    小雨   东风 <3级    25     多云  东北风 <3级    12         详情
      丰台    小雨   北风 <3级    28     多云   北风 <3级    17         详情
      石景山   小雨  西北风 <3级    28     多云   北风 <3级    16         详情
      大兴    小雨  东北风 <3级    28     多云  东北风 <3级    16         详情
      房山    小雨   北风 <3级    28     多云  东北风 <3级    15         详情
      密云    小雨  东南风 <3级    27     多云  东北风 <3级    14         详情
      门头沟   小雨   北风 <3级    27     多云   北风 <3级    16         详情
      平谷    小雨  东南风 <3级    27     多云   东风 <3级    14         详情
      东城    小雨  东南风 <3级    27     多云  东北风 <3级    16         详情
      西城    小雨  西北风 <3级    28     多云   北风 <3级    15         详情

In [7]:
url = 'https://fund.eastmoney.com/fund.html'
pd.read_html(url)[1]

,热点推荐 手机买基金,基金数据,基金交易登录|开户,服务指南
0,自选基金基金比较 稳健理财收益计算 主题基金基金经理 基金研究基 金 吧,基金净值投顾管家 基金排行定投排行 基金评级基金分红 基金公司私募基金,活 期 宝私 募 宝 指 数 宝高端理财 基金导购收益排行 稳健理财基金优选,帮助中心 机构指南 意见反馈 安全保障

In [3]:
dick = 'fuck'
dick

'fuck'

In [4]:
import cv2
img = cv2.imread(r'F:\VSCode Files\Web\Notes\Statics\Image\test.png')
img.shape

(440, 472, 3)

In [5]:
m = 3
while m<10:
    n=2
    while n<=m-1:
        if m%n==0:
            break
        if n==m-1:
            print(m)
        n+=1
    m+=1

3
5
7

In [6]:
kk = [1,2,3,4,5,6,7,8,9]
tu = tuple(kk)
print(type(*tu))

TypeError: type() takes 1 or 3 arguments