In [1]:
import pandas as pd

url = 'http://www.weather.com.cn/textFC/hb.shtml'
pd.read_html(url, header=1, index_col=[0, 1])[0]

          天气现象      风向风力  最高气温 天气现象.1    风向风力.1  最低气温 Unnamed: 8
省/直辖市 城市
北京    北京     晴   西南风 <3级    35      晴  西南风 3-4级    22         详情
      海淀     晴  西南风 3-4级    35      晴   西南风 <3级    19         详情
      朝阳     晴   西南风 <3级    35      晴  西南风 3-4级    22         详情
      顺义     晴   西南风 <3级    35      晴   西南风 <3级    21         详情
      怀柔     晴   西南风 <3级    35      晴   东北风 <3级    20         详情
      通州     晴   西南风 <3级    35      晴   西南风 <3级    21         详情
      昌平     晴    南风 <3级    35      晴    北风 <3级    19         详情
      延庆     晴    南风 <3级    33      晴   西北风 <3级    18         详情
      丰台     晴   西南风 <3级    35      晴   西南风 <3级    20         详情
      石景山    晴   西南风 <3级    35      晴   西南风 <3级    20         详情
      大兴     晴   西南风 <3级    35      晴   西南风 <3级    21         详情
      房山     晴   西南风 <3级    35      晴   西南风 <3级    19         详情
      密云     晴   西南风 <3级    34      晴    南风 <3级    18         详情
      门头沟    晴    南风 <3级    35      晴   西南风 <3级    20         详情
      平谷     晴    西风 <3级    35      晴   西南风 <3级    18         详情
      东城     晴   西南风 <3级    35      晴  西南风 3-4级    22         详情
      西城     晴  西南风 3-4级    35      晴   西南风 <3级    19         详情

In [4]:
url = 'https://fund.eastmoney.com/fund.html'
pd.read_html(url)[0]

  您已经选择的基金
0     隐藏清空

In [3]:
dick = 'fuck'
dick

'fuck'

In [4]:
import cv2
img = cv2.imread(r'F:\VSCode Files\Web\Notes\Statics\Image\test.png')
img.shape

(440, 472, 3)

In [5]:
m = 3
while m<10:
    n=2
    while n<=m-1:
        if m%n==0:
            break
        if n==m-1:
            print(m)
        n+=1
    m+=1

3
5
7

In [6]:
kk = [1,2,3,4,5,6,7,8,9]
tu = tuple(kk)
print(type(*tu))

TypeError: type() takes 1 or 3 arguments